language: node_js
node_js:
  - "stable"
env:
  global:
    - secure: gE94p4lNCyykk224+raAgKdXVETUc6K+sYxw5OXUgRrF/44USzaL7lh9wiXE9z+rJpiA6art4Wlu3SzDTi02UpOOvbHC57wEGXJk93oMB8N1LLT2+MQ1juBDMTmQpWdF2dQNISYpMUjOzvSTZOrrV6DAtTaictWj+2sAT0cashg=
    - secure: EvBp6t/20uEfr68XZd2y7bAqgwgZMvbQdE8HDgxbELghiJvZ/PqMo8UcWmBLPyymiDL5XRFtUDOW0Tt1tcQnF6q/D6gIz6+3SLtB/pUcejh3HDTuNM0vqHyCAWbXt+nGnTCAM32sS6tveY7eM8F2SjGmxf1ARLjvMBKwBKSs40c=
before_script:
  - npm install -g grunt-cli
script:
  - grunt build
  - grunt test_and_coveralls
  - grunt saucelabs || true
