language: node_js
node_js:
- stable
- node
cache: yarn

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
  - stage: deploy
    env: DEPLOY=releases
    script: yarn pack
    deploy:
    - provider: releases
      api_key:
        secure: G3GhG2rFCnsTS+LffmIL6Vq84mf2BDkjqpyNIGled2sQMTwYQjKQzPAE6D5vClSc69BqnAyBniZi13/SfNlfXk/UunIDuMSSFdjikYCZECyTBvNj1A0F16yacYUYMzQGsXpyFvNUWoQB/TuyRkLUv78Nw+EkBtdZoIZVXQUFOScOpdIYZSVUPpgjF4tb7srh4qb3iuZU4rxiKb7/EK/5gnzuIG4wqQaHWLUO400IQXjQRQhfBzPr2wE8y7HWd9u82JZJfXho7QFgOnYd6DY3ECYHZ4VnZT2HdAfJY7CUWaMIV1Kkb4kSBMS0rs+D4CvFLo3B4983bgeo/9vWN9DeeTCGVNkqcwSr+FXmv8e/bX98mibk4gUvfo3F+4msxakbeP7iQP3aWXKpVoHOYV1ryoMWqizLi2DalLSNTC9JVe7/uqKwjjRUxPYHQMabWNDHvpmgVDwjWiSH/8FIa/2YITznjlLJy0WjuTwcpt6eOnW7k5vRSgld4rXCSb2LKjQKxI5NE4xVvUO3lOSP8zL6mzi+/oQNRY0n7iX+UEV+7Lpcr50szWwHo4Ezm/auPCmCHkIolc0Kz20bKAEO69LdX4PKwC6dzeDShtLc7BXKY/k+rqPA8jyCdpOS2tZ67bQGDxkaLuiRam+HKkKGKQLWOX2NhrdK36w8DL0rY+cRTR0=
      file_glob: true
      file: scrypt-async-modern-*.tgz
      skip_cleanup: true
      on:
        tags: true
  - stage: deploy
    env: DEPLOY=npm
    script: skip
    deploy:
    - provider: npm
      email: charles@cretezy.com
      api_key:
        secure: Iygd0dBsRQ10xfuUQyaeHS1DoVWcl+UMgJI1J5q+YmWc46SPS1RI0oGZ75UCT1PxJKTz39yu2tiLB3q/3T41vaMel9nEm5XtOyv0PcML6LM4ak+HC7b6HGGV9B4QtBgSdDSr/H4uu40ICzAC37i6ACPN83b1EupbxMtt1YUZ7b9So8fhGdTqw+LXH1ohCFKZ7OQ+bgsSkL5u6IVOVNBpFSVxfP5zsFwjj+9HWiW/JdBtW4xgT/e03w+f/qZdclxQYJNkX24L7/6fFV7zpqbjSZXojvXtDCtZGTLsPPsP+eUX6WNTWYUi/RhWPBRFbOHgGvY83IuTe+Jkg+5NYjJiA6hG5RAiA0MOK+ZnF0yLwExDnCwhYpvbfyLIjNwnmkLIAc/b8zLJIgz+XGc4FU4U21bOao/omqzmftzTIOhODgDIQczssH0ztRvNIaBQ80wtd3ahfsBNNTIZRB5GvvJhzqQXcijPDm57XViaK5i4ymsbBhQ2Zj7U7430Q3ewwi0ZOtSQmppLdYTFiVrun5JExgLdwvGJulGL1lTk+VRTPaLcowbrx7psa5aHKB3P7co1rCeKXCt13G1PXy8L/ZLs/Cz7E9LKQc1aWbcnR1s+E3wH31pNishbBd6LrIs3hfLuqhYu1LC/q0sGt41Lea7+kIVT6OrLkdDYLk8yfoRMi70=
      skip_cleanup: true
      on:
        tags: true
